# Generated by Django 5.1.1 on 2024-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapping',
            name='scrapping_limit',
            field=models.IntegerField(default=0),
        ),
    ]
